### ISSUE TITLE
Python 3 is having issue in def write_message()

### ISSUE THREAD

**Issue by Zainab1256** [guilhermef/tornado-eventsource#7]
When the server suppose to consume and then send message to client(Browser) it does not accept messages on the server and showed an error message.

![errortopost](https://user-images.githubusercontent.com/76491551/102932932-149bd300-44c3-11eb-84d4-b9628d6b473c.PNG)

**Comment by guilhermef** [comment]
@Zainab1256 I do need to do some updates on this code, but I haven't used it in a while.
Can you create a PR to address this issue?
I'm afraid that I won't have much time to fix it before next year.

**Comment by Zainab1256** [comment]
Dear Sir,

I am a research students from Pakistan and have to make a Server-sent
event's server that receives messages from rabbitmq . In this regards I
need to Implement it with tornado. I tried many ways but failed can you
please see this code and help me to run my server. I have running rabbitmq
producer only issue is in server.py.
You are expert in it your 5 minutes will helpme a lot. I am struck on this
point for many months.
I will be very grateful if your positive response received.

**Comment by guilhermef** [comment]
@Zainab1256 I've updated the code to support python3 and uploaded a release candidate: https://github.com/guilhermef/tornado-eventsource/releases/tag/2.0.0rc2
